In [3]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr2=np.arange(1,10).reshape(3,3)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr3=np.random.rand(3,5,5)
arr3

array([[[0.448329  , 0.2982069 , 0.29921625, 0.61439629, 0.29377823],
        [0.05591017, 0.55672738, 0.16735721, 0.54183228, 0.96096978],
        [0.26173787, 0.55120618, 0.118061  , 0.58226651, 0.5526186 ],
        [0.49634691, 0.06416011, 0.66252765, 0.65053449, 0.24789085],
        [0.80848427, 0.30953715, 0.18561838, 0.98097763, 0.01027056]],

       [[0.69335274, 0.77543039, 0.4934401 , 0.56009811, 0.09541102],
        [0.82610955, 0.06443654, 0.67755364, 0.71681911, 0.93931405],
        [0.17509718, 0.85839387, 0.77200038, 0.50981595, 0.2921119 ],
        [0.25760386, 0.3722172 , 0.59025957, 0.81687928, 0.14392357],
        [0.4317836 , 0.63811885, 0.88331929, 0.47781989, 0.19172878]],

       [[0.7397569 , 0.24399834, 0.12796679, 0.53530236, 0.0963096 ],
        [0.40505453, 0.67567498, 0.22322568, 0.35263545, 0.67714479],
        [0.01621307, 0.02399916, 0.69690247, 0.74260083, 0.4044493 ],
        [0.92010663, 0.90814593, 0.83765785, 0.90698569, 0.31016925],
        [0.54484

In [17]:
print(arr.shape)
print(arr.size)
print(arr.dtype)

print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

(10,)
10
int64
(3, 3)
9
int64
(3, 5, 5)
75
float64


In [19]:
#Task 2
 
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr=np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(arr[0:3])
print(arr[0:9:2])
print(arr[::-1])


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [41]:
#Task 3
A=np.random.randint(1,20,5)
B=np.random.randint(1,20,5)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print(add)
print(sub)
print(mul)
print(div)

dot=np.dot(A,B)
print(dot)

[2 1 9 3 7]
[ 1  5 19  7 11]
[ 3  6 28 10 18]
[  1  -4 -10  -4  -4]
[  2   5 171  21  77]
[2.         0.2        0.47368421 0.42857143 0.63636364]
276


In [35]:
print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

9.0
8.0
4.69041575982343
22.0


In [ ]:

print(np.max(B),"Index->",np.argmax(B))

9 Index-> 2
19 Index-> 2


In [43]:
#Task 4
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
a1=arr.reshape(4,3)
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
a1.transpose().shape



(3, 4)

In [58]:
#Task 5
a=np.random.randint(10,50,15)
a

array([21, 44, 31, 16, 39, 15, 16, 14, 41, 42, 33, 44, 36, 38, 21],
      dtype=int32)

In [59]:
print(a[a>25])

[44 31 39 41 42 33 44 36 38]


In [60]:
a[a<30]=0
a

array([ 0, 44, 31,  0, 39,  0,  0,  0, 41, 42, 33, 44, 36, 38,  0],
      dtype=int32)

In [64]:
print(np.count_nonzero(a%5==0))

6


In [66]:
#Task 6
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [69]:
arr=np.eye(4,dtype="int")
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [71]:
arr=np.random.randint(1,100,20)
arr

array([53, 87, 90, 24, 73, 15, 23,  7, 82, 68, 67, 42, 26, 62, 56, 48, 77,
       69, 41, 46], dtype=int32)

In [72]:
sorted=np.sort(arr)
sorted

array([ 7, 15, 23, 24, 26, 41, 42, 46, 48, 53, 56, 62, 67, 68, 69, 73, 77,
       82, 87, 90], dtype=int32)

In [74]:
print(sorted[-5::][::-1])

[90 87 82 77 73]


In [81]:
#Task 7
import time
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start_time = time.time()

C = np.dot(A, B)
print(C,"/n")

det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")

if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True

end_time = time.time()

print(f"Operation end time :{end_time} \n")

elapsed_time = end_time - start_time

print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {elapsed_time:.4f} seconds")

[[26.62089123 23.32498624 24.85731893 ... 25.04194201 25.17705585
  28.51473346]
 [24.64059285 23.39462846 22.28668752 ... 26.19782345 24.19123056
  25.45014088]
 [20.32143906 20.07262198 19.12414261 ... 20.55946766 20.89616908
  23.63907873]
 ...
 [24.79143851 23.65543955 22.93779467 ... 24.03074389 24.92707844
  26.77001675]
 [25.91405125 25.02938548 24.88974065 ... 25.82656489 25.86086755
  28.25997234]
 [26.66680278 23.6738779  23.99147813 ... 25.50164029 25.08054253
  27.2930874 ]] /n
Determinant of the result: 2.436872482617207e+51 

Operation end time :1751727507.332811 

Matrix is invertible.
Inverse matrix calculated successfully.
[[ 0.53736683 -0.36958558 -1.48394006 ...  0.62190446  0.81925457
   1.03017765]
 [ 0.68011848  0.44595717 -0.02494913 ...  0.52092297  0.14039641
  -1.13542106]
 [-0.55402663  0.42587805  1.286737   ... -0.86431826 -1.64429557
  -0.89176825]
 ...
 [-0.65950379 -0.96853242  1.92650383 ... -2.20980615 -1.68882557
   1.51789003]
 [ 0.08633373 -0.035914